### ISSUE TITLE
Add .DS_Store files to a default .gitignore for each gitified package

### ISSUE THREAD

**Issue by cooljeanius** [pajp/apple-opensource-mirror#1]
Some of the Apple opensource packages have `.DS_Store`s in them; these should be removed with a default `.gitignore` file.

**Comment by pajp** [comment]
Thanks for the feedback! I intend to fix this before I import the 10.8.4 sources, but I don't think I will retroactively re-import all previous versions because it'd be a rather big project.

**Comment by cooljeanius** [comment]
> Thanks for the feedback!

You're welcome!

> I intend to fix this before I import the 10.8.4 sources, but I don't think I will retroactively re-import all previous versions because it'd be a rather big project.

It's pretty much just the older sources that I've been noticing these in; I doubt they'll be in any of the ones released for 10.8.4 (Apple has gotten better about excluding them lately)

**Comment by cooljeanius** [comment]
actually never mind; it's probably better to leave them the way they came...
